// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJsnyEA-9o4MTTpem2LC9hycCXf2a_DU',
    appId: '1:294655674353:web:f69c236ffe07d1d80aa650',
    messagingSenderId: '294655674353',
    projectId: 'proyecto-firebase-aab2e',
    authDomain: 'proyecto-firebase-aab2e.firebaseapp.com',
    storageBucket: 'proyecto-firebase-aab2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUM_fznJjd7ZTiQM-0mM0OYIMaqYVVYY',
    appId: '1:294655674353:android:b7e7337649a0e7d60aa650',
    messagingSenderId: '294655674353',
    projectId: 'proyecto-firebase-aab2e',
    storageBucket: 'proyecto-firebase-aab2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhTqw1Np2nLGBB5bgod7Vai7rBuqw4vA',
    appId: '1:294655674353:ios:42b7944fc31db57b0aa650',
    messagingSenderId: '294655674353',
    projectId: 'proyecto-firebase-aab2e',
    storageBucket: 'proyecto-firebase-aab2e.appspot.com',
    iosBundleId: 'com.example.proyectoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhTqw1Np2nLGBB5bgod7Vai7rBuqw4vA',
    appId: '1:294655674353:ios:7d76ad9d815ac9800aa650',
    messagingSenderId: '294655674353',
    projectId: 'proyecto-firebase-aab2e',
    storageBucket: 'proyecto-firebase-aab2e.appspot.com',
    iosBundleId: 'com.example.proyectoFirebase.RunnerTests',
  );
}
